name: Qodana

on:
push:
branches:
- main
pull_request:
jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  - name: Run Run Qodana Community Community Scan
    uses: JetBrains/qodana-action@v2025.1
    with:
          community: true
      community: true
      upload-result: true
```
